# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 785efbc261ee9340a88021df4630b93fc8966fc3e15a74b0a619c1b54f80c341adae0e6e829ec3c3ae173c28af186542f2ed9fe0cb3e9f9f36146ab2f281487e

test:
  secret_key_base: a9bf4ec7ed0306f7907e54777495e8ff0aaed9fedfe383527412ab9dc30228869baf424e9f9bccb5fec3dcffef686fb17962dfcaf137329acfc6db1a96bb6280

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
