# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 696b833a0719344e65615da8281a6207a5d33abbc95f282b2785b1459f4bf01d39bd5497f3e31864a3e1696ab189988c79b8bd358f24e4a2f6e4797bfbcb83d3

test:
  secret_key_base: 3da47c881c8778a2963681a8fda1abd83501a499ef08b3de4a508a96e859e30b48b727762fda2c93cb4ef25e797fe2be4b81fa5065b4ee41da4d790f60b5e56f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
